server:
  applicationConnectors:
    - type: http
      port: 9091
  adminConnectors: []
template: Hello ServerResource. I am %s!
defaultName: Stranger ClientResource

blobsConfiguration:
  areBlobsEnabled: true
  store:
    name: FileStore
    blobsRelativePath: /blobs
